"""Concentrated-liquidity pools in the replay engine: validation, replay, quotes, fills, valuation, views.

The pack is built in-process with ``build_pack``. Its tape is generated by driving a ``ClPoolState``
with the same exact v3 math the engine uses, so every ``cl_swap`` row's after-values are
self-consistent and the no-agent replay must reconcile with zero mismatches.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from market_replay.broker.ledger import AGENT_AVAILABLE, AGENT_PENDING, AGENT_RESERVED
from market_replay.datasets.builder import build_pack, make_period
from market_replay.datasets.execution_params import historical_research_params
from market_replay.datasets.pack import Pack
from market_replay.datasets.validator import reconcile_no_agent, validate_pack
from market_replay.domain.models import Rights, Universe
from market_replay.domain.status import DataOrigin, OrderState, PoolModel, TokenBehavior, UseStatus
from market_replay.engine.session import Session
from market_replay.engine.simulation import HOOKED_LAUNCH_WINDOW_MS, Simulation, SubmitRejected
from market_replay.venues.clmm.math import Q96
from market_replay.venues.clmm.pool import ClPoolState

CHAIN = 8453
WETH = f"{CHAIN}:0x4200000000000000000000000000000000000006"
TOKEN = f"{CHAIN}:0x" + "ab" * 20
TOKEN3 = f"{CHAIN}:0x" + "de" * 20
POOL1 = f"{CHAIN}:uniswap_v3:0x" + "cd" * 20
POOL2 = f"{CHAIN}:uniswap_v4:0x" + "02" * 32
HOOKS = "0xc1a4" + "0" * 32 + "a8cc"
FEE, SPACING = 10000, 200
FEE2, DYN_FEE = 3000, 5000  # pool 2 is a v4 pool whose hook sets a dynamic fee per swap
L1, L2 = 10**21, 5 * 10**20
IN_AMOUNT = 10**18
B0 = 30_000_000  # first block == prehistory start
INTERVAL_MS = 2000
DELAY_MS = 4000
START_MS = 1_756_997_600_000  # period start (absolute); prehistory begins 30 minutes earlier
PRE_MS = START_MS - 1_800_000
END_MS = START_MS + 3_600_000
POOL2_BLOCK = B0 + 1500  # inside the period (period starts at block B0 + 900)
BANK = 10**19


def block_time(b: int) -> int:
    return PRE_MS + (b - B0) * INTERVAL_MS


class World:
    """Drives ``ClPoolState`` instances and records their events as tape rows."""

    def __init__(self) -> None:
        self.rows: list[dict[str, Any]] = []
        self.seq = 0

    def _base(self, pool: str, block: int, log_index: int) -> dict[str, Any]:
        self.seq += 1
        return {"seq": self.seq, "block": block, "log_index": log_index, "time_utc_ms": block_time(block), "pool": pool, "tx": "0x" + f"{self.seq:064x}", "wallet": "0x" + "77" * 20, "available_utc_ms": block_time(block) + DELAY_MS, "availability_basis": "reconstructed_with_delay_model"}

    def init(self, st: ClPoolState, block: int) -> None:
        self.rows.append({**self._base(st.key, block, 0), "kind": "cl_init", "sqrt_price_x96": str(st.sqrt_price_x96), "tick": st.tick})

    def modify(self, st: ClPoolState, block: int, lo: int, hi: int, delta: int, *, apply: bool = True) -> None:
        if apply:
            st.apply_modify_liquidity(lo, hi, delta)
        self.rows.append({**self._base(st.key, block, 5), "kind": "cl_modify", "tick_lower": lo, "tick_upper": hi, "liquidity_delta": str(delta)})

    def swap(self, st: ClPoolState, block: int, zero_for_one: bool, amount_in: int = IN_AMOUNT, fee_pips: int | None = None) -> None:
        a0, a1, sqrt, liq, tick = st.swap(zero_for_one, amount_in, None, fee_pips)
        self.rows.append({**self._base(st.key, block, 2), "kind": "cl_swap", "amount0": str(a0), "amount1": str(a1), "sqrt_price_x96_after": str(sqrt), "liquidity_after": str(liq), "tick_after": tick, "fee_pips": st.fee_pips if fee_pips is None else fee_pips})


def make_cl_pack(out_dir: Path, *, tamper_seq: int | None = None, overdraw: bool = False) -> Pack:
    """Two CL pools: POOL1 (v3, live before the window, initial state from the driving state) and POOL2
    (v4 with hooks and a dynamic fee, initialized inside the period)."""
    world = World()
    p1 = ClPoolState.initialize(POOL1, WETH, TOKEN, FEE, SPACING, Q96, model="uniswap_v3_cl")
    p1.apply_modify_liquidity(-20000, 20000, L1)
    p1.apply_modify_liquidity(-2000, 2000, L2)
    # a few swaps before the window move the price off the initialization tick
    for i in range(5):
        p1.swap(i % 2 == 0, IN_AMOUNT)
    initial = p1.copy()
    # prehistory: swaps every 10 blocks, one burn inside the prehistory
    for i, b in enumerate(range(B0, B0 + 900, 10)):
        world.swap(p1, b, zero_for_one=i % 3 == 0)
        if i == 40:
            world.modify(p1, b, -2000, 2000, -L2 // 10)
    # period: swaps every 10 blocks
    for i, b in enumerate(range(B0 + 900, B0 + 2700, 10)):
        world.swap(p1, b, zero_for_one=i % 3 == 1)
    if overdraw:
        # a burn larger than the whole position: no consistent state can honour it
        world.modify(p1, B0 + 2650, -20000, 20000, -(L1 + 1), apply=False)
    # pool 2: initialized inside the period, one mint, a dynamic-fee swap, one more swap
    p2 = ClPoolState.initialize(POOL2, WETH, TOKEN3, FEE2, 60, Q96, model="uniswap_v4_cl")
    world.init(p2, POOL2_BLOCK)
    world.modify(p2, POOL2_BLOCK + 1, -1200, 1200, L1)
    world.swap(p2, POOL2_BLOCK + 2, zero_for_one=True, fee_pips=DYN_FEE)
    world.swap(p2, POOL2_BLOCK + 20, zero_for_one=False, fee_pips=DYN_FEE)
    tape = sorted(world.rows, key=lambda r: (r["block"], r["log_index"], r["seq"]))
    for i, r in enumerate(tape, start=1):
        r["seq"] = i
    if tamper_seq is not None:
        row = next(r for r in tape if r["kind"] == "cl_swap" and r["seq"] >= tamper_seq)
        row["sqrt_price_x96_after"] = str(int(row["sqrt_price_x96_after"]) + 1)
    assets = [
        {"key": WETH, "chain_id": CHAIN, "address": WETH.split(":")[1], "decimals": 18, "symbol": "WETH", "is_numeraire": True, "discovery_available_utc_ms": PRE_MS},
        {"key": TOKEN, "chain_id": CHAIN, "address": TOKEN.split(":")[1], "decimals": 18, "symbol": None, "is_numeraire": False, "discovery_available_utc_ms": PRE_MS},
        {"key": TOKEN3, "chain_id": CHAIN, "address": TOKEN3.split(":")[1], "decimals": 18, "symbol": None, "is_numeraire": False, "discovery_available_utc_ms": PRE_MS},
    ]
    pools = [
        {
            "key": POOL1, "chain_id": CHAIN, "protocol": "uniswap_v3", "address": POOL1.split(":")[2], "model": "uniswap_v3_cl",
            "asset0": WETH, "asset1": TOKEN, "fee_numerator": 1_000_000 - FEE, "fee_denominator": 1_000_000, "fee_pips": FEE, "tick_spacing": SPACING, "hooks": None,
            "created_block": B0 - 5000, "created_time_utc_ms": block_time(B0 - 5000), "discovery_available_utc_ms": block_time(B0 - 5000) + DELAY_MS,
            "initial_sqrt_price_x96": str(initial.sqrt_price_x96), "initial_tick": initial.tick, "initial_liquidity": str(initial.liquidity),
            "initial_ticks": [[str(t), str(net), str(gross)] for t, (net, gross) in sorted(initial.ticks.items())],
            "initial_state_block": B0 - 1, "initial_state_basis": "test_driving_state", "supported_by_cpmm": False, "supported_by_clmm": True,
        },
        {
            "key": POOL2, "chain_id": CHAIN, "protocol": "uniswap_v4", "address": POOL2.split(":")[2], "model": "uniswap_v4_cl",
            "asset0": WETH, "asset1": TOKEN3, "fee_numerator": 1_000_000 - FEE2, "fee_denominator": 1_000_000, "fee_pips": FEE2, "tick_spacing": 60, "hooks": HOOKS,
            "created_block": POOL2_BLOCK, "created_time_utc_ms": block_time(POOL2_BLOCK), "discovery_available_utc_ms": block_time(POOL2_BLOCK) + DELAY_MS,
            "initial_sqrt_price_x96": None, "initial_tick": None, "initial_liquidity": None, "initial_ticks": [],
            "initial_state_block": None, "initial_state_basis": "pool_initialized_inside_window", "supported_by_cpmm": False, "supported_by_clmm": True,
        },
    ]
    coverage = {"schema": "coverage_v1", "basis": "test", "intervals": [{"object_ref": k, "field": "swaps", "start_utc_ms": PRE_MS, "end_utc_ms": END_MS, "state": "completed_and_checked", "evidence": "generated in-process"} for k in (POOL1, POOL2)]}
    return build_pack(
        out_dir,
        origin=DataOrigin.HISTORICAL_RECONSTRUCTION,
        chain="base",
        chain_id=CHAIN,
        scope_label="test_cl_engine",
        title_private="test concentrated-liquidity engine pack",
        period=make_period(START_MS, END_MS, PRE_MS),
        universe=Universe(factories=[], pool_models=[PoolModel.UNISWAP_V3_CL, PoolModel.UNISWAP_V4_CL], quote_asset=WETH, selection_rule_version="test", candidate_count=2, selected_count=2),
        assets=assets,
        pools=pools,
        tape=tape,
        params=historical_research_params(block_interval_ms=INTERVAL_MS, availability_delay_ms=DELAY_MS),
        coverage=coverage,
        numeraire=WETH,
        numeraire_alias="NATIVE",
        numeraire_decimals=18,
        token_behavior=TokenBehavior.ASSUMED_STANDARD_TRANSFER,
        availability_model={"kind": "constant_delay_from_block_time", "delay_ms": DELAY_MS},
        rights=Rights(storage_basis="test", local_processing_basis="test", redistribution="not_cleared"),
        qualification=UseStatus.RESEARCH,
        inventory={"unsupported": []},
    )


@pytest.fixture(scope="module")
def cl_pack(tmp_path_factory: pytest.TempPathFactory) -> Pack:
    return make_cl_pack(tmp_path_factory.mktemp("cl") / "pack")


def sim_for(pack: Pack, bankroll: int = BANK) -> Simulation:
    return Simulation(pack, bankroll_raw=bankroll, engine_seed="e")


def cl_fields(p: ClPoolState) -> tuple[int, int, int, dict]:
    return p.sqrt_price_x96, p.tick, p.liquidity, dict(p.ticks)


# ---------------------------------------------------------------- validator


def test_cl_pack_validates_as_research_with_zero_mismatches(cl_pack: Pack):
    report = validate_pack(cl_pack)
    gates = {g["gate"]: g for g in report["gates"]}
    recon = gates["execution_state"]["reconciliation"]
    swaps = sum(1 for r in cl_pack.tape if r["kind"] == "cl_swap")
    assert recon["checkpoints"] == swaps > 0
    assert recon["mismatch_count"] == 0 and recon["fidelity_flag_count"] == 0
    assert gates["execution_state"]["status"] == "passed" and gates["execution_state"]["pools_missing_initial_state"] == []
    assert gates["mechanics"]["status"] == "passed"
    assert report["resulting_qualification"] == "research" and cl_pack.validation["resulting_qualification"] == "research"
    full = reconcile_no_agent(cl_pack)
    assert full["final_reserves"] == {} and set(full["final_cl_state"]) == {POOL1, POOL2}
    assert full["final_state"][POOL2]["model"] == "uniswap_v4_cl" and full["final_cl_state"][POOL2]["initialized_ticks"] == 2


def test_cl_model_marked_cpmm_fails_mechanics(cl_pack: Pack):
    pack = Pack.load(cl_pack.path)
    pack.pools[POOL1] = pack.pools[POOL1].model_copy(update={"supported_by_cpmm": True})
    gates = {g["gate"]: g for g in validate_pack(pack)["gates"]}
    assert gates["mechanics"]["status"] == "failed" and POOL1 in gates["mechanics"]["detail"]


# ---------------------------------------------------------------- replay


def test_prehistory_and_full_replay_keep_private_equal_to_reference(cl_pack: Pack):
    sim = sim_for(cl_pack)
    assert sim.now_ms == 0 and sim.cursor > 0
    assert cl_fields(sim.pools[POOL1]) == cl_fields(sim.ref_pools[POOL1])
    sim.process_until(sim.end_ms)
    assert sim.reconciliation_mismatches == [] and sim.fidelity_flags == []
    for k in (POOL1, POOL2):
        assert cl_fields(sim.pools[k]) == cl_fields(sim.ref_pools[k])
    # external trades became observations with the CL fields set
    trades = sim.obs[POOL1].trades
    assert trades and all(t.origin == "external" and t.sqrt_price_x96_after is not None and t.liquidity_after is not None for t in trades)
    assert trades[-1].sqrt_price_x96_after == sim.pools[POOL1].sqrt_price_x96
    assert (trades[-1].reserve0_after, trades[-1].reserve1_after) == sim.pools[POOL1].virtual_reserves()


def test_tampered_after_price_is_exactly_one_mismatch(tmp_path: Path):
    pack = make_cl_pack(tmp_path / "tampered", tamper_seq=100)
    assert pack.validation["resulting_qualification"] == "diagnostic_only"
    recon = reconcile_no_agent(pack)
    assert recon["mismatch_count"] == 1 and recon["mismatches"][0]["delta_sqrt_price_x96"] == -1
    sim = sim_for(pack)
    sim.process_until(sim.end_ms)
    assert len(sim.reconciliation_mismatches) == 1 and sim.reconciliation_mismatches[0]["delta_sqrt_price_x96"] == -1


def test_overdrawn_modify_flags_environment_fidelity_limit(tmp_path: Path):
    pack = make_cl_pack(tmp_path / "overdraw", overdraw=True)
    sim = sim_for(pack)
    sim.process_until(sim.end_ms)
    codes = {f.code for f in sim.fidelity_flags if f.pool == POOL1}
    assert "ENVIRONMENT_FIDELITY_LIMIT" in codes and sim.fidelity_failed[POOL1] == "ENVIRONMENT_FIDELITY_LIMIT"
    with pytest.raises(SubmitRejected) as e:
        sim.quote(POOL1, WETH, 10**15)
    assert e.value.code == "ENVIRONMENT_FIDELITY_LIMIT"


# ---------------------------------------------------------------- broker


def test_quote_equals_pool_quote_on_a_copy(cl_pack: Pack):
    sim = sim_for(cl_pack)
    sim.process_until(60_000)
    pool = sim.pools[POOL1]
    amt = 10**17
    q = sim.quote(POOL1, WETH, amt)
    expected = pool.copy().quote(WETH, amt)
    assert q.amount_out == expected.amount_out > 0 and q.asset_out == TOKEN
    assert (q.fee_num, q.fee_den) == (1_000_000 - FEE, 1_000_000)
    assert (q.reserve_in, q.reserve_out) == pool.depth_for(WETH)
    assert q.capacity_ok
    # the quote did not move the pool
    assert cl_fields(pool) == cl_fields(sim.ref_pools[POOL1])


def test_submit_fills_with_quoted_amount_and_balances_ledger(cl_pack: Pack):
    sim = sim_for(cl_pack)
    sim.process_until(60_000)
    pool = sim.pools[POOL1]
    amt = 10**17
    q = sim.quote(POOL1, WETH, amt)
    h0 = sim.state_hash()
    o, created = sim.submit(pool_key=POOL1, asset_in=WETH, asset_out=TOKEN, amount_in=amt, min_amount_out=q.amount_out, deadline_ms=10**7, idempotency_key="cl1", quote_id=q.quote_id)
    assert created
    sim.process_until(sim.now_ms + 10_000)
    assert o.state == OrderState.CONFIRMED and o.amount_out == q.amount_out
    assert sim.state_hash() != h0
    # ledger: principal left the agent, output arrived, every entry balanced per asset
    assert sim.ledger.balance(AGENT_AVAILABLE, TOKEN) == q.amount_out
    assert sim.ledger.balance(AGENT_RESERVED, WETH) == 0 and sim.ledger.balance(AGENT_PENDING, TOKEN) == 0
    assert sim.ledger.balance(AGENT_AVAILABLE, WETH) == BANK - amt - cl_pack.params.gas_cost
    for e in sim.ledger.entries:
        per_asset: dict[str, int] = {}
        for leg in e.legs:
            per_asset[leg.asset] = per_asset.get(leg.asset, 0) + leg.delta
        assert all(v == 0 for v in per_asset.values())
    own = [t for t in sim.obs[POOL1].trades if t.origin == "own"]
    assert len(own) == 1 and own[0].amount_out == q.amount_out and own[0].order_id == o.order_id
    assert (own[0].sqrt_price_x96_after, own[0].tick_after, own[0].liquidity_after) == (pool.sqrt_price_x96, pool.tick, pool.liquidity)
    # the private state now differs from the reference by the agent's impact and later flow keeps replaying
    assert pool.sqrt_price_x96 != sim.ref_pools[POOL1].sqrt_price_x96
    sim.process_until(sim.end_ms)
    assert sim.reconciliation_mismatches == [] and not any(f.code == "EXTERNAL_SWAP_FAILED_ON_PRIVATE_STATE" for f in sim.fidelity_flags)


def test_value_portfolio_prices_holding_through_cl_pool(cl_pack: Pack):
    sim = sim_for(cl_pack)
    sim.process_until(60_000)
    amt = 10**17
    sim.submit(pool_key=POOL1, asset_in=WETH, asset_out=TOKEN, amount_in=amt, min_amount_out=0, deadline_ms=10**7, idempotency_key="v")
    sim.process_until(sim.now_ms + 10_000)
    qty = sim.ledger.balance(AGENT_AVAILABLE, TOKEN)
    v = sim.value_portfolio()
    h = next(x for x in v.holdings if x["asset"] == TOKEN)
    assert h["class"] == "priced_liquidatable" and h["pool"] == POOL1
    assert h["value"] == sim.pools[POOL1].copy().quote(TOKEN, qty).amount_out
    assert v.complete and v.equity == v.cash_available + v.cash_reserved + v.cash_pending + h["value"] - v.liquidation_gas
    # the valuation branch did not touch the private pool
    assert sim.pools[POOL1].sqrt_price_x96 == sim.obs[POOL1].trades[-1].sqrt_price_x96_after


def test_capacity_limit_uses_virtual_depth(cl_pack: Pack):
    sim = sim_for(cl_pack)
    sim.process_until(60_000)
    depth_in, _ = sim.pools[POOL1].depth_for(WETH)
    big = depth_in * cl_pack.params.capacity.max_input_bps_of_reserve // 10_000 + 1
    with pytest.raises(SubmitRejected) as e:
        sim.submit(pool_key=POOL1, asset_in=WETH, asset_out=TOKEN, amount_in=big, min_amount_out=0, deadline_ms=10**7, idempotency_key="big")
    assert e.value.code == "MODEL_CAPACITY_LIMIT"


# ---------------------------------------------------------------- in-window initialization


def test_pool_initialized_inside_window_becomes_tradable_after_cl_init(cl_pack: Pack):
    sim = sim_for(cl_pack)
    init_ms = block_time(POOL2_BLOCK) - START_MS
    assert sim.cl_init_ms[POOL2] == init_ms
    sim.process_until(init_ms - 10_000)
    assert POOL2 not in sim.pools
    with pytest.raises(SubmitRejected) as e:
        sim.quote(POOL2, WETH, 10**15)
    assert e.value.code == "NOT_YET_DISCOVERED"
    sim.process_until(init_ms + DELAY_MS + 3 * INTERVAL_MS)
    pool = sim.pools[POOL2]
    assert isinstance(pool, ClPoolState) and pool.liquidity == L1 and pool.fee_pips == FEE2
    # the dynamic-fee swap was replayed with the row's fee, so private == reference
    assert cl_fields(pool) == cl_fields(sim.ref_pools[POOL2])
    # a hooked pool offers no route inside its launch window (MEV modules), then trades normally
    with pytest.raises(SubmitRejected) as e:
        sim.quote(POOL2, WETH, 10**15)
    assert e.value.code == "NO_ROUTE" and "launch window" in e.value.message
    sim.process_until(init_ms + HOOKED_LAUNCH_WINDOW_MS)
    q = sim.quote(POOL2, WETH, 10**15)
    assert q.amount_out == pool.copy().quote(WETH, 10**15).amount_out > 0


# ---------------------------------------------------------------- session views


def test_session_exposes_cl_pool_and_liquidity_views(cl_pack: Pack):
    s = Session.create(session_id="s", pack=cl_pack, bankroll_raw=BANK, mask_seed="m", engine_seed="e")
    env = s.handle("r1", "markets.list", {"filters": {"execution_supported_only": True}})
    assert env.status == "ok", env.error
    items = {i["pool_id"]: i for i in env.data["items"]}
    pid1 = s.alias.pool(POOL1)
    assert set(items) == {pid1}  # POOL2 is not discoverable yet
    p = items[pid1]
    assert p["venue_model"] == "uniswap_v3_cl" and p["execution_supported"] is True
    assert p["fee_pips"] == FEE and p["tick_spacing"] == SPACING and "hooks" not in p
    env = s.handle("r2", "market.liquidity", {"pool_id": pid1})
    assert env.status == "ok", env.error
    d = env.data
    st = s.sim.pools[POOL1]
    assert d["model"] == "uniswap_v3_cl" and d["sqrt_price_x96"] == str(st.sqrt_price_x96) and d["tick"] == st.tick and d["liquidity"] == str(st.liquidity)
    x, y = st.virtual_reserves()
    assert d["virtual_depth"] == [{"asset_id": "NATIVE", "depth_raw": str(x)}, {"asset_id": s.alias.asset(TOKEN), "depth_raw": str(y)}]
    assert d["fee_pips"] == FEE and "active tick range" in d["note"]
    near = d["initialized_ticks_near_price"]
    assert [t["tick"] for t in near] == [-20000, -2000, 2000, 20000] and all(isinstance(t["liquidity_net"], str) for t in near)
    # quote, submit, advance and portfolio through the session
    env = s.handle("r3", "broker.quote", {"pool_id": pid1, "asset_in": "NATIVE", "amount_in_raw": str(10**17)})
    assert env.status == "ok", env.error
    assert env.data["fee"] == {"numerator": 1_000_000 - FEE, "denominator": 1_000_000, "note": "embedded in output; not charged again"}
    env = s.handle("r4", "broker.submit", {"pool_id": pid1, "asset_in": "NATIVE", "asset_out": s.alias.asset(TOKEN), "amount_in_raw": str(10**17), "min_amount_out_raw": "0", "deadline_ms": 10**7, "idempotency_key": "k"})
    assert env.status == "ok", env.error
    s.handle("r5", "clock.advance", {"to_ms": s.now + 10_000})
    env = s.handle("r6", "portfolio.get", {})
    holding = next(h for h in env.data["valuation"]["holdings"] if h["asset_id"] == s.alias.asset(TOKEN))
    assert holding["class"] == "priced_liquidatable" and holding["pool_id"] == pid1
    # the v4 pool with hooks: listed after its discovery, hook address aliased, never raw
    s.handle("r7", "clock.advance", {"to_ms": block_time(POOL2_BLOCK) - START_MS + DELAY_MS + 10_000})
    pid2 = s.alias.pool(POOL2)
    env = s.handle("r8", "markets.get", {"pool_id": pid2})
    assert env.status == "ok", env.error
    assert env.data["venue_model"] == "uniswap_v4_cl" and env.data["execution_supported"] is True
    assert env.data["hooks"].startswith("hook_") and HOOKS not in env.data["hooks"]
    env = s.handle("r9", "market.liquidity", {"pool_id": pid2})
    assert env.status == "ok" and env.data["liquidity"] == str(L1) and env.data["fee_pips"] == FEE2
